apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: waterdrips-s3
  namespace: openfaas-fn
spec:
  encryptedData:
    s3-access-key: AgASQIJqKfDQL1MLlZMnpNGcZrGm3EjgitQHR3cXw+LCvofRLmCTDPIe1ODrQYs9VnXQdu48ZcztUKZrFBsDYUqYjnCmtZMAQE8WmxDJxkXFpkIqOhHf9WFJIVsvUuaJH1k4EeAfCoGst0JTis81V2gJR0lczlbDFDqMntQ9shyGHqsaPwcVS6ijKmnbAf76QntfFd+N8R1gSeQtk2fnFpvLCX0uwfKL6YuAiObQSkwFoYKHIFAgjtE55BvvX+zvZ2fCewEpvgSNuE/bXWJ1UraWk1kjIEEEGb7Id9MGHvBHfS9Q01ieLFEuGuzP5T/nSUl/En/I9skZq+Ab8F7cHExf6Vvxrwizo6MFga/SDVoQDspUXJHhCZPwc0mFFpDBizOZMQX1u1Wl84Kge2RaGlRTMXbkS1JlBqAhTTgHPHw++ZzS0baWOayswKX+zBaBrgPLtYxhXIaImWd2jp1+xKAzvxPW7LLxFbJW+doxp2Xja1QzFtw8/jycnP3trzIur/BwZlRzwvumn25NCyGcfcvU1aA2d2W17nU3HFAxWlVNksgyydpcfI08lBXd7G0/nK6yDWrLfnyIEMIBwUq0pew/xM+ZMBnA84lPOFtqS4SA0dx/JF5/AHcB0lJZlMQ0v4FhbwWJmMUqQ5dEBzntR5phg82E+LWfqoAZmd/g6s0G61mkcDsFunxFAeVpE7KZ8bu/fV7CrchD0PHkpmDQKGZu8SDM+LIRmX7Y
    s3-secret-key: AgBQj5lsSwGNsca/TBu7j2YfaXMD029AONVJGySyW7LK2u6p6PiY0A+0LeYohcyayMQXC1nA1fO6TEKCpUzA7LEwOqVnZf99kF1eVhXJ6Dyx+5sFo0xtnZ/FVhXou2eyYGgNXNAhaJlIGjm6LAsEBcqssCo6v8SSuxyicN0XQYEAW59ieCxvDDM3SWIrYUapQ1DqphMFlgQXSME1PaB8EvSBe3+czTYaFV4F/JbumKuMWP/GeAwrcl4i+SpB7NTp6+Npf6y5IShRwRHEqU0AEj8KvAQlrK8REI1KRUHeM0rhvlM9ojEKcswEG1Jo5UB7mspBsKavii5AsGCaWE/BavigOCMONIUDrmEwMLf8NXF0KdE1nwAnTJ3BhS/XKqHvQROmts0i5IO12+LpJQJmj6i/Qw2Nqg8kkdTpzOZv3RUrDw4MLDeyBmhtdEe7ckpDth6sXzjUDji6P1ulOIWxuuxzF3TUrI1qkcTMI+6/pYWfHEn83eerPMO+R4QqW1aBacEAi7kKz7haJ3KfYFPV323MFFyv9b17qykXLUTAY8jH/BOlhMGSk/LIWoXWYN+rAYOB3p+S+7mc9rYRJWntUSjQXZ5q7VkBDn72Hpqkz/n0q+woegJgMHMw2wvCZ/rKtPhaLvhzeXRW1/f4urxBQfbiN8s/SfdOh3k4SruyHcVm95fOZpaQ2kHhp1k+cq/QpBykpTh6rvUC+niJojk3T18nd4cD2ZKhvQy1
  template:
    metadata:
      creationTimestamp: null
      name: waterdrips-s3
      namespace: openfaas-fn

